version: "3.7"

networks:
  parseable:

services:

  parseable:
    image: parseable/parseable:latest
    command: ["parseable", "local-store"]
    ports:
      - "8000:8000"
    environment:
      - P_FS_DIR=/parseable/data
      - P_STAGING_DIR=/parseable/staging
      - P_USERNAME=admin
      - P_PASSWORD=admin
    networks:
      - parseable
    volumes:
      - ./data:/parseable/data
      - ./staging:/parseable/staging

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:8.10.0-amd64
    ports:
      - "9200:9200"
      - "50000:50000/tcp"
      - "50000:50000/udp"
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - parseable
    depends_on:
      - parseable

  solana-test-validator-sologger-logstash:
    image: brytelands/sologger-logstash-geyser-plugin:latest
    container_name: solana-test-validator-sologger-logstash
    tty: true
    ports:
      - "1024:1024"
      - "9900:9900"
      - "8900:8900"
      - "8899:8899"
    networks:
      - parseable
    depends_on:
      - logstash
    volumes:
      - type: bind
        source: ./log4rs-config.yml
        target: /config/local/log4rs-config.yml
      - type: bind
        source: ./sologger-config.json
        target: /config/local/sologger-config.json
